## Excepciones

A veces nos podemos encontrar con errores de ejecución en nuestro código. Por ejemplo al hacer las conversiones.

No hay que confundir estos errores con los errores de sintaxis por código mal formado.

Existe un mecanismo para tratar estos errore en tiempo de ejecución. 

Decimos que cuando se produce un error de estos se genera una **excepción**, y cuando se produce una nuestro programa se termina en esa línea.

Podemos hacer que nuesto código capture estas excepciones y así evitar que nuestro código finalice. Para ello usaremos la estructura **try: ... except :**, que se divide en 2 partes, a las que llamaremos bloques:

* Ponemos **try:** antes de la parte inicial donde pensamos que se puede producir la excepción. 
* Ponemos **except:** para indicar el código que queremos que se genera si se produce la excepción.

Para delimitar cláramente el código de cada parte añadimos unos espacios (normalmente 4) antes de las líneas de codigo de cada bloque.

Python no utiliza delimitadores para indicar los bloques de codigo como otros lenguajes (**{...}** en C, C++ o Java), si no que la indentación de las líneas (los espacios iniciales), marca estos bloques.


```python
# Comprobar si una cadena es o no un numero
s = input('Introduzca un númoer entero: ')
try: # Comienzo del bloque try
    valorInt = int(s)  # Se produce una excepción
    print('Es entero') # Esta línea no se ejecuta
except: # Comienzo del bloque except
    prtin('No es entero')

print('Hemos terminado') # Esta línea no está dentro de los bloques
```

Existen diferentes tipos de Excepciones, según el error que se produzca. Las que se generan por conversión decimos que son de tipo **ValueError**

